[32m2021-06-07 15:19:21[0m - dagster - [34mDEBUG[0m - camera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - LOGS_CAPTURED - Started capturing logs for solid: merge_dfs.
[32m2021-06-07 15:19:22[0m - dagster - [34mDEBUG[0m - camera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - STEP_START - Started execution of step "merge_dfs".
[32m2021-06-07 15:19:22[0m - dagster - [34mDEBUG[0m - camera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - LOADED_INPUT - Loaded input "df" using input manager "geojson", from output "camera" of step "create_geojson"
/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/inputs.py:160: DtypeWarning: Columns (0,1,2,3,4,5,6,7,9,14,15,16,17,20,21,26,27,28,29,30,31) have mixed types.Specify dtype option on import or set low_memory=False.
  yield _load_input_with_input_manager(loader, load_input_context)
[32m2021-06-07 15:19:23[0m - dagster - [34mDEBUG[0m - camera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - LOADED_INPUT - Loaded input "metadata" using input manager "metadata_root"
[32m2021-06-07 15:19:23[0m - dagster - [34mDEBUG[0m - camera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - STEP_INPUT - Got input "df" of type "Any". (Type check passed).
[32m2021-06-07 15:19:24[0m - dagster - [34mDEBUG[0m - camera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - STEP_INPUT - Got input "metadata" of type "Any". (Type check passed).
[32m2021-06-07 15:19:24[0m - dagster - [34mERROR[0m - [31mcamera_pipeline - 9a6e429e-b18b-4de8-bad8-75d3d43d5215 - 1648 - merge_dfs - STEP_FAILURE - Execution of step "merge_dfs" failed.

dagster.core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/execute_plan.py", line 193, in _dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/execute_step.py", line 305, in core_dagster_event_sequence_for_step
    for user_event in check.generator(
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/execute_step.py", line 64, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/execute_step.py", line 599, in _user_event_sequence_for_step_compute_fn
    for event in iterate_with_context(
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/utils/__init__.py", line 380, in iterate_with_context
    with context_fn():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 40, in solid_execution_error_boundary
    with raise_execution_interrupts():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/errors.py", line 152, in raise_execution_interrupts
    with raise_interrupts_as(DagsterExecutionInterruptedError):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/utils/interrupts.py", line 73, in raise_interrupts_as
    raise error_cls()
[0m
