[32m2021-07-16 16:10:09[0m - dagster - [34mDEBUG[0m - camera_pipeline - 0f5623a1-f020-4f2e-8233-fa986d231895 - 12339 - update_metadata - LOGS_CAPTURED - Started capturing logs for solid: update_metadata.
[32m2021-07-16 16:10:10[0m - dagster - [34mDEBUG[0m - camera_pipeline - 0f5623a1-f020-4f2e-8233-fa986d231895 - 12339 - update_metadata - STEP_START - Started execution of step "update_metadata".
[32m2021-07-16 16:10:10[0m - dagster - [34mERROR[0m - [31mcamera_pipeline - 0f5623a1-f020-4f2e-8233-fa986d231895 - 12339 - update_metadata - STEP_FAILURE - Execution of step "update_metadata" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "df" of step "update_metadata"::

fiona.errors.DriverError: 'data/output/import_viewcones.geojson' not recognized as a supported file format.

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/inputs.py", line 502, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/mnt/e/situated-views-etl/solids/utils.py", line 52, in load_input
    return gpd.read_file(file_path + ".geojson")  # retorno um df
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/geopandas/io/file.py", line 160, in _read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/fiona/env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/fiona/__init__.py", line 257, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/fiona/collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
[0m
