[32m2021-07-22 12:59:46[0m - dagster - [34mDEBUG[0m - apis_pipeline - a38cc234-c330-442b-8736-3092c0da43f7 - 2487 - update_metadata - LOGS_CAPTURED - Started capturing logs for solid: update_metadata.
[32m2021-07-22 12:59:46[0m - dagster - [34mDEBUG[0m - apis_pipeline - a38cc234-c330-442b-8736-3092c0da43f7 - 2487 - update_metadata - STEP_START - Started execution of step "update_metadata".
[32m2021-07-22 12:59:46[0m - dagster - [34mDEBUG[0m - apis_pipeline - a38cc234-c330-442b-8736-3092c0da43f7 - 2487 - update_metadata - LOADED_INPUT - Loaded input "df" using input manager "pandas_csv", from output "api_omeka" of step "omeka_dataframe"
[32m2021-07-22 12:59:46[0m - dagster - [34mERROR[0m - [31mapis_pipeline - a38cc234-c330-442b-8736-3092c0da43f7 - 2487 - update_metadata - STEP_FAILURE - Execution of step "update_metadata" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "metadata" of step "update_metadata"::

FileNotFoundError: [Errno 2] No such file or directory: 'data/output/metadata.csv'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/inputs.py", line 502, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/storage/root_input_manager.py", line 159, in load_input
    return self._load_fn(context)
  File "/mnt/e/situated-views-etl/solids/utils.py", line 102, in root_input_csv
    return pd.read_csv(context.resource_config)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
[0m
