[32m2021-06-07 12:40:24[0m - dagster - [34mDEBUG[0m - calatog_main - fac7fc1f-8126-46e9-88d6-75fe67b1a9c4 - 1317 - xml_to_df - LOGS_CAPTURED - Started capturing logs for solid: xml_to_df.
[32m2021-06-07 12:40:25[0m - dagster - [34mDEBUG[0m - calatog_main - fac7fc1f-8126-46e9-88d6-75fe67b1a9c4 - 1317 - xml_to_df - STEP_START - Started execution of step "xml_to_df".
[32m2021-06-07 12:40:25[0m - dagster - [34mERROR[0m - [31mcalatog_main - fac7fc1f-8126-46e9-88d6-75fe67b1a9c4 - 1317 - xml_to_df - STEP_FAILURE - Execution of step "xml_to_df" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "root" of step "xml_to_df"::

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/y/getty/cumulus.xml'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/inputs.py", line 510, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/storage/root_input_manager.py", line 159, in load_input
    return self._load_fn(context)
  File "/mnt/d/IMS/situated-views/bin/solids/utils.py", line 80, in root_input_xml
    with open(path, encoding="utf8") as f:
[0m
