[32m2021-07-22 15:44:38[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 37ca0b5a-766b-4a85-afaf-aa9edd71d030 - 4256 - format_date - LOGS_CAPTURED - Started capturing logs for solid: format_date.
[32m2021-07-22 15:44:38[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 37ca0b5a-766b-4a85-afaf-aa9edd71d030 - 4256 - format_date - STEP_START - Started execution of step "format_date".
[32m2021-07-22 15:44:38[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 37ca0b5a-766b-4a85-afaf-aa9edd71d030 - 4256 - format_date - LOADED_INPUT - Loaded input "df" using input manager "io_manager", from output "result" of step "extract_dimensions"
[32m2021-07-22 15:44:38[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 37ca0b5a-766b-4a85-afaf-aa9edd71d030 - 4256 - format_date - STEP_INPUT - Got input "df" of type "Any". (Type check passed).
[32m2021-07-22 15:44:40[0m - dagster - [34mERROR[0m - [31mcumulus_pipeline - 37ca0b5a-766b-4a85-afaf-aa9edd71d030 - 4256 - format_date - STEP_FAILURE - Execution of step "format_date" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "format_date"::

AttributeError: 'Timestamp' object has no attribute 'dt'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/utils/__init__.py", line 383, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/e/situated-views-etl/solids/cumulus.py", line 190, in format_date
    df = df.apply(date_to_string, axis=1)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/frame.py", line 7552, in apply
    return op.get_result()
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/apply.py", line 305, in apply_series_generator
    results[i] = self.f(v)
  File "/mnt/e/situated-views-etl/solids/cumulus.py", line 182, in date_to_string
    return row["Date"].dt.strftime("%Y") + " circa"
[0m
