[32m2021-06-07 15:03:36[0m - dagster - [34mDEBUG[0m - calatog_main - 42803037-38c1-45ea-9984-dd4a3cf06793 - 551 - merge_dfs - LOGS_CAPTURED - Started capturing logs for solid: merge_dfs.
[32m2021-06-07 15:03:37[0m - dagster - [34mDEBUG[0m - calatog_main - 42803037-38c1-45ea-9984-dd4a3cf06793 - 551 - merge_dfs - STEP_START - Started execution of step "merge_dfs".
[32m2021-06-07 15:03:37[0m - dagster - [34mDEBUG[0m - calatog_main - 42803037-38c1-45ea-9984-dd4a3cf06793 - 551 - merge_dfs - LOADED_INPUT - Loaded input "df" using input manager "pandas_csv", from output "catalog" of step "extract_dimensions"
[32m2021-06-07 15:03:38[0m - dagster - [34mERROR[0m - [31mcalatog_main - 42803037-38c1-45ea-9984-dd4a3cf06793 - 551 - merge_dfs - STEP_FAILURE - Execution of step "merge_dfs" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "metadata" of step "merge_dfs"::

FileNotFoundError: [Errno 2] No such file or directory: 'data-out/metadata.csv'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/execution/plan/inputs.py", line 510, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/dagster/core/storage/root_input_manager.py", line 159, in load_input
    return self._load_fn(context)
  File "/mnt/d/IMS/situated-views/bin/solids/utils.py", line 75, in root_input
    return pd.read_csv(context.config['path'])
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/parsers.py", line 1362, in _open_handles
    self.handles = get_handle(
  File "/home/pitanga/.local/share/virtualenvs/situated-views-XI40jPuu/lib/python3.8/site-packages/pandas/io/common.py", line 642, in get_handle
    handle = open(
[0m
