[32m2021-06-23 10:21:47[0m - dagster - [34mDEBUG[0m - apis_pipeline - 10667221-493a-4d42-8c3a-f03e9b868242 - 433 - update_metadata - LOGS_CAPTURED - Started capturing logs for solid: update_metadata.
[32m2021-06-23 10:21:47[0m - dagster - [34mDEBUG[0m - apis_pipeline - 10667221-493a-4d42-8c3a-f03e9b868242 - 433 - update_metadata - STEP_START - Started execution of step "update_metadata".
[32m2021-06-23 10:21:48[0m - dagster - [34mDEBUG[0m - apis_pipeline - 10667221-493a-4d42-8c3a-f03e9b868242 - 433 - update_metadata - LOADED_INPUT - Loaded input "df" using input manager "pandas_csv", from output "api_wikidata" of step "wikidata_dataframe"
[32m2021-06-23 10:21:48[0m - dagster - [34mERROR[0m - [31mapis_pipeline - 10667221-493a-4d42-8c3a-f03e9b868242 - 433 - update_metadata - STEP_FAILURE - Execution of step "update_metadata" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "metadata" of step "update_metadata"::

TypeError: string indices must be integers

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/inputs.py", line 510, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/storage/root_input_manager.py", line 159, in load_input
    return self._load_fn(context)
  File "/mnt/d/ims/situated-views/bin/solids/utils.py", line 79, in root_input_csv
    return pd.read_csv(context.resource_config["env"])
[0m
