[32m2021-06-24 14:44:08[0m - dagster - [34mDEBUG[0m - catalog_pipeline - c4c531d3-c9f1-470c-a7e2-57f69a7dc701 - 15584 - xml_to_df - LOGS_CAPTURED - Started capturing logs for solid: xml_to_df.
[32m2021-06-24 14:44:08[0m - dagster - [34mDEBUG[0m - catalog_pipeline - c4c531d3-c9f1-470c-a7e2-57f69a7dc701 - 15584 - xml_to_df - STEP_START - Started execution of step "xml_to_df".
[32m2021-06-24 14:44:09[0m - dagster - [34mERROR[0m - [31mcatalog_pipeline - c4c531d3-c9f1-470c-a7e2-57f69a7dc701 - 15584 - xml_to_df - STEP_FAILURE - Execution of step "xml_to_df" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "root" of step "xml_to_df"::

AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'set_index'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/inputs.py", line 510, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/storage/root_input_manager.py", line 159, in load_input
    return self._load_fn(context)
  File "/mnt/d/ims/situated-views/bin/solids/utils.py", line 91, in root_input_xml
    root = (tree.getroot()).set_index("id")
[0m
