[32m2021-06-24 14:24:18[0m - dagster - [34mDEBUG[0m - metadata_pipeline - d6b1465c-40e1-404d-b644-33649d312b2b - 15431 - create_metadata - LOGS_CAPTURED - Started capturing logs for solid: create_metadata.
[32m2021-06-24 14:24:19[0m - dagster - [34mDEBUG[0m - metadata_pipeline - d6b1465c-40e1-404d-b644-33649d312b2b - 15431 - create_metadata - STEP_START - Started execution of step "create_metadata".
[32m2021-06-24 14:24:19[0m - dagster - [34mERROR[0m - [31mmetadata_pipeline - d6b1465c-40e1-404d-b644-33649d312b2b - 15431 - create_metadata - STEP_FAILURE - Execution of step "create_metadata" failed.

dagster.core.errors.DagsterExecutionLoadInputError: Error occurred while loading input "camera" of step "create_metadata"::

AttributeError: 'InputContext' object has no attribute 'respurce_config'

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/inputs.py", line 510, in _load_input_with_input_manager
    value = input_manager.load_input(context)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/storage/root_input_manager.py", line 159, in load_input
    return self._load_fn(context)
  File "/mnt/d/ims/situated-views/bin/solids/utils.py", line 97, in root_input_geojson
    return gpd.read_file(context.respurce_config)
[0m
