[32m2021-07-23 16:05:56[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 471221d1-7a1c-4b1d-a05d-a0cf57c40382 - 851 - format_date - LOGS_CAPTURED - Started capturing logs for solid: format_date.
[32m2021-07-23 16:05:56[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 471221d1-7a1c-4b1d-a05d-a0cf57c40382 - 851 - format_date - STEP_START - Started execution of step "format_date".
[32m2021-07-23 16:05:56[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 471221d1-7a1c-4b1d-a05d-a0cf57c40382 - 851 - format_date - LOADED_INPUT - Loaded input "df" using input manager "io_manager", from output "result" of step "extract_dimensions"
[32m2021-07-23 16:05:56[0m - dagster - [34mDEBUG[0m - cumulus_pipeline - 471221d1-7a1c-4b1d-a05d-a0cf57c40382 - 851 - format_date - STEP_INPUT - Got input "df" of type "Any". (Type check passed).
[32m2021-07-23 16:05:58[0m - dagster - [34mERROR[0m - [31mcumulus_pipeline - 471221d1-7a1c-4b1d-a05d-a0cf57c40382 - 851 - format_date - STEP_FAILURE - Execution of step "format_date" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "format_date"::

ValueError: Cannot mask with non-boolean array containing NA / NaN values

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/utils/__init__.py", line 383, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/dagster/core/execution/plan/compute_generator.py", line 65, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/e/situated-views-etl/solids/cumulus.py", line 184, in format_date
    "%Y"
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/indexing.py", line 666, in __setitem__
    indexer = self._get_setitem_indexer(key)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/indexing.py", line 609, in _get_setitem_indexer
    return self._convert_tuple(key, is_setter=True)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/indexing.py", line 734, in _convert_tuple
    idx = self._convert_to_indexer(k, axis=i, is_setter=is_setter)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/indexing.py", line 1192, in _convert_to_indexer
    if com.is_bool_indexer(key):
  File "/home/pitanga/.local/share/virtualenvs/situated-views-etl-KhhASCmw/lib/python3.6/site-packages/pandas/core/common.py", line 134, in is_bool_indexer
    raise ValueError(na_msg)
[0m
