[32m2021-06-24 18:25:50[0m - dagster - [34mDEBUG[0m - catalog_pipeline - 4c728f88-36f3-4522-9ad4-2009fcc11046 - 16788 - xml_to_df - LOGS_CAPTURED - Started capturing logs for solid: xml_to_df.
[32m2021-06-24 18:25:50[0m - dagster - [34mDEBUG[0m - catalog_pipeline - 4c728f88-36f3-4522-9ad4-2009fcc11046 - 16788 - xml_to_df - STEP_START - Started execution of step "xml_to_df".
[32m2021-06-24 18:25:51[0m - dagster - [34mDEBUG[0m - catalog_pipeline - 4c728f88-36f3-4522-9ad4-2009fcc11046 - 16788 - xml_to_df - LOADED_INPUT - Loaded input "root" using input manager "xml_root"
[32m2021-06-24 18:25:51[0m - dagster - [34mDEBUG[0m - catalog_pipeline - 4c728f88-36f3-4522-9ad4-2009fcc11046 - 16788 - xml_to_df - STEP_INPUT - Got input "root" of type "Any". (Type check passed).
[32m2021-06-24 18:25:51[0m - dagster - [34mERROR[0m - [31mcatalog_pipeline - 4c728f88-36f3-4522-9ad4-2009fcc11046 - 16788 - xml_to_df - STEP_FAILURE - Execution of step "xml_to_df" failed.

dagster.core.errors.DagsterExecutionStepExecutionError: Error occurred while executing solid "xml_to_df"::

TypeError: 'NoneType' object is not subscriptable

Stack Trace:
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/execution/plan/utils.py", line 42, in solid_execution_error_boundary
    yield
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/utils/__init__.py", line 382, in iterate_with_context
    next_output = next(iterator)
  File "/home/pitanga/.local/share/virtualenvs/situated-views-yLYNqPII/lib/python3.8/site-packages/dagster/core/definitions/decorators/solid.py", line 307, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/mnt/d/ims/situated-views/bin/solids/catalog.py", line 18, in xml_to_df
    for thing in root[0][0]:
[0m
